version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=production

  frontend:
    build: ./frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
